#!/bin/bash

# Remove
sed -E '/(^.*[^#]|^)##[^.#].*$/d' fanboy-addon.txt |
sed -E '/^\[.*$/d;/^!\sChecksum:.*$/d;/!\sThis\slist\sexpires.*$/d' |
perl -pe 's/^(?!~).+##.*\.(facebook|fb_iframe_widget|google_?plus|latestshowsocial|twitter|social(ize)?)([.#[].*)?$//g' |
perl -pe 's/^(?!~).+##.*#(facebook|social|socialBlock|tweets)([.#[].*)?$//g' |
sed -E '/^.*##.*\.(facebook|twitter)([.#[].*)?$/d' |
sed -E '/^\|\|vkontakte\.ru\^\$.*$/d' |
sed -E '/^\/btn-share-fb\.$/d' |
perl -pe 's/^(?!@@).*\/share\.js\$.*$//g' |
# Fix
sed -E 's/^\[.*\]$//g' |
sed -E 's/^!\s*Title:/! /g' |
sed -E 's/^!\s*Expires:.*$//g' |
sed -E 's/^!\s*(License|Email|Homepage|Forums):/! FAL \1:/g' |
sed -E 's/^(.*)\$(domain=.*),(.*)$/\1$\3,\2/g' |
sed -E 's/object_subrequest/object-subrequest/g' |
# Clean and Write
sed -r '/^\s*$/d' > fanboy-addon-light.txt
