#!/bin/bash
svn update
./checksum.pl advblock.txt
./checksum.pl antinuha.txt
./checksum.pl bitblock.txt
./checksum.pl cntblock.txt
svn diff advblock.txt
svn diff antinuha.txt
svn diff bitblock.txt
svn diff cntblock.txt
svn --editor-cmd gedit commit
sleep 60
