#!/bin/bash
svn update
./hash.pl advblock.txt
./hash.pl antinuha.txt
./hash.pl bitblock.txt
./hash.pl cntblock.txt
svn diff advblock.txt
svn diff antinuha.txt
svn diff bitblock.txt
svn diff cntblock.txt
svn --editor-cmd gedit commit
sleep 1
rm -f svn-commit.*
