#!/bin/bash
echo -- List of latest updates ----------------------------------------------
svn log --revision BASE:HEAD
echo -- Difference between BASE and HEAD revisions of advblock.txt ----------
svn diff --revision BASE:HEAD advblock.txt
echo -- Difference between BASE and HEAD revisions of bitblock.txt ----------
svn diff --revision BASE:HEAD bitblock.txt
echo -- Difference between BASE and HEAD revisions of cntblock.txt ----------
svn diff --revision BASE:HEAD cntblock.txt
echo -- Updating...
svn update
