#!/bin/bash
# How it works:
#  * SED:
#    1. Move lists of domains one row below to make sure they will pass to the last phase.
#    2. Move hiding rules below lists of domains and mark them as trash
#  * SED:
#    1. Replace all rows starting with '||' or '! ||' or protocol://, with text starting after these characters but before /, $, ^ or * (blocking rules).
#  * SED
#    1. Remove all rows not starting with text, number, '~' or underscore (remove all garbage except things starting with underscore because it isn't in \W).
#    2. Remove all rows starting with underscore (they are garbage as well).
#    3. Remove all rows with dot in the end (incomplete domains).
#    4. Replace ',' and '|' with <new row> character (break lists of domains).
#    5. Remove '~' characters.
#    6. Remove rows without '.' character (obvious non-domains or first level domains like com/ru/ua/...).
#    7. Remove emtpy rows.
#  * Sort things and remove clones.
#  * Save result to file.
sed 's/[$,]domain=/\n/g;s/##/\n!/g' advblock.txt | sed -r 's#^(\!\s\|{2}|\|{2}|\w*:?/{2})(\w[^/$^*]*).*$#\2#g' | sed -r '/^(\W|~).*$/d;/^_.*$/d;/^.*\.$/d;s/[,|]/\n/g;s/~//g;/^[^.]*$/d;/^ *$/d' | sort -fu > deadhosts.txt

