name: Update cntblock Timestamp

on:
  push:
    branches:
      - master
    paths:
      - 'cntblock.txt'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Replace timestamp with real date
        run: |
          REAL_DATE=$(date -u +"%d %b %Y %H:%M UTC")
          sed -i "s/\(! Last modified:\).*/\1 $REAL_DATE/g" cntblock.txt

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git diff --quiet || (git add cntblock.txt && git commit -m "Autoupdate cntblock timestamp [skip ci]" && git push)
